version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: db_redis

  app:
    build:
      context: .
    env_file: .env
    container_name: fastapi
    entrypoint: ["/app/sh/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app